version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3001}:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:1}
      - VITE_AUTH_ENABLED=${VITE_AUTH_ENABLED:-true}
      - VITE_MAX_FILE_SIZE=${VITE_MAX_FILE_SIZE:-10485760}
      - VITE_ALLOWED_FILE_TYPES=${VITE_ALLOWED_FILE_TYPES:-pdf,jpg,png,jpeg}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev